[package]
distribution = "2201.11.0"
org = "ballerina"
name = "xsdtool"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["xsd"]
repository = "https://github.com/ballerina-platform/xsd-tools"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false
